### ISSUE TITLE
Configurable keyword for parsing

### ISSUE THREAD

**Issue by legwinskij** [MikhailKravets/mkdocs_puml#20]
**Is your feature request related to a problem? Please describe.**
First of all, thank you very much for this great plugin! Just one question, I use GitLab for some of the projects, and GitLab supports [inline plantuml rendering](https://docs.gitlab.com/ee/administration/integration/plantuml.html) natively throughout the whole website. Only issue is that their integration looks for keyword `plantuml` instead of `puml`.

**Describe the solution you'd like**
Would it be possible to extend configuration for customisable keyword within `mkdocs.yml`? e.g. something like this:

```yml
plugins:
    - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 8
        puml_keyword: plantuml # default puml
```

**Describe alternatives you've considered**
Switch from `puml` keyword to `plantuml`, but that could break backwards compatibility, and having this configurable might be bulletproof going forward, these "flavored" Markdowns are not standardized per se.
