### ISSUE TITLE
The access of the PlantUML doesn't work due to the self-signed certificate of my company.

### ISSUE THREAD

**Issue by pur-jus** [MikhailKravets/mkdocs_puml#26]
**Describe the bug**
The access of the PlantUML doesn't work due to the self-signed certificate of my company.

**To Reproduce**
1. Include the plantuml plugin within the mkdocs YAML
``` yaml
plugins:
   - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 8
```
2. Run `mkdocs serve`
3. The following error is displayed
``` pwsh
SSLError: HTTPSConnectionPool(host='www.plantuml.com', port=443): Max retries exceeded with url: /plantuml/svg/ut8eBaaiAYdDpU5oLD2rKt2oKW0BA6GavgKKPoHcft8vWSGThHIIS_ABKv747LBpKa3w00== (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)')))
```

**Desktop:**
 - Win10
 - Python 3.11.1 (virtual env)
 - Mkdocs-material 9.1.6
