### ISSUE TITLE
Uuid cannot be replaced by SVG file

### ISSUE THREAD

**Issue by HouzeZHANG** [MikhailKravets/mkdocs_puml#38]
Hello community,

I am trying to use inline plantuml to insert uml svg in mkdocs webpage. 

I followed the readme.md steps to configure and you can check one part of my `mkdocs.yml` file as below:

```yml
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
      remove_comments: true
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml
      num_workers: 8
      puml_keyword: puml
      verify_ssl: true
```

After inserting the code segment of plantuml in the markdown file like below:

```puml
@startuml
Bob -> Alice : hello
@enduml
```

What I got is this part is replaced by an **uuid**. I test with localhost:8000:

```
8ca8b494-ec31-49b1-ad47-7e8d955749e4
```

It seems that my webpage doesn't reveive the response of the plantuml server after replacing the code segment by uuid.

I tried build_plantuml plugin which is an non-inline support for mkdocs and it seems that the server url is correct because it works.

Anyone know why it happens? Why mkdocs_plantuml cannot replace its uuid :) ?
