### ISSUE TITLE
Fix static files included in sdist

### ISSUE THREAD

**Issue by MikhailKravets** [MikhailKravets/mkdocs_puml#62]
**Describe the bug**

Currently, `pyproject.toml` contains these lines

```toml
[tool.flit.sdist]
# Specify the files to include in the source distribution
include = ["mkdocs_puml/static/puml.css"]
```

despite it contains only `puml.css`, flit packs `mkdocs_puml` with all its content.

Either remove `include = ["mkdocs_puml/static/puml.css"]` entry or consider moving the `static` out of `mkdocs_puml`.
