### ISSUE TITLE
Support POST so send bigger files

### ISSUE THREAD

**Issue by cre8** [MikhailKravets/mkdocs_puml#91]
**Is your feature request related to a problem? Please describe.**
In my current CICD the pipeline is failing from time to time with 400 errors. Since there is no better feedback error message, I would assume that it is based on the size limit of the image (but I wasn't able to figure out which image it is to debug it).
According to the web at least docker images of them are supporting POST (it's not activated for the hosted instance to avoid huge requests).

So my question would be if we could add a new parameter that would use POST instead of GET (default would be GET to not break existing systems).

**Describe the solution you'd like**
A new config variable to choose POST instead of GET

**Describe alternatives you've considered**
None

**Additional context**
Here is the log of my failed cdcd job: https://gitlab.opencode.de/bmi/eudi-wallet/eidas-2.0-architekturkonzept/-/jobs/631142#L211
It is strange that is worked on the second run, so maybe the problem is at another point.

Thank you :)

**Comment by MikhailKravets** [comment]
Hi @cre8, the problem is different. This is because the trottle rate of GitHub. `mkdocs-puml` grabs themes directly from https://raw.githubusercontent.com/MikhailKravets/mkdocs_puml. So, if you have a lot of diagrams and re-render them a lot, GitHub returns 400 (or 429) error and PlantUML proxies this error to the user. This is why it seems that it works randomly. The best solution to this would be to host your [desired themes](https://github.com/MikhailKravets/mkdocs_puml/tree/master/themes) on your own server

**Comment by cre8** [comment]
Mmh. but with this config:

```
    - plantuml:
        puml_url: !ENV [PUML_URL, 'https://www.plantuml.com/plantuml/']
        puml_keyword: plantuml
        verify_ssl: false
        cache:
          backend: local
          local:
            path: "diagrams"
            join_project_name: false
        theme:
          enabled: false
```
I have disabled the themes and therefore I would assume that there are no calls to Github. Or are there any other resources that are fetched from the server?
